### ISSUE TITLE
Extra whitespace in generated HTML

### ISSUE THREAD

**Issue by jasalt** [babashka/toolbox#10]
I noticed that the repo HTML doc generation script includes some extra whitespace characters on empty lines.

Just a minor cosmetic thing but thought to note as it could point to another issue somewhere else.

![generates whitespace](https://github.com/user-attachments/assets/ab813c36-8638-4a57-ae9b-96d7fc5eec48)

Screenshot from Emacs Magit with whitespace marked red by `ethan-wspace` package, configured with:

```
(use-package ethan-wspace
  :blackout t
  :config
  (setq mode-require-final-newline nil)
  (global-ethan-wspace-mode 1)
  )
```

**Comment by borkdude** [comment]
Thanks but this is likely an issue with a library we're using and not an issue with this project as such:

https://github.com/babashka/toolbox/blob/96270965bb31da99b3338dc25a38decb097293e3/bb.edn#L1
